version: "3.8"

services:
  prefect_agent:
    image: python:3.10-slim
    command: >
      sh -c "pip install -r /app/requirements.txt &&
      prefect cloud login --key ${PREFECT_CLOUD_API_KEY} --workspace ${PREFECT_CLOUD_WORKSPACE} &&
      cd /app/src &&
      prefect agent start -p default-agent-pool"
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./src:/app/src
      - ./infrastructure/scheduling:/app/infrastructure/scheduling
    restart: always
    network_mode: "host"
    env_file:
      - .env
